# Generated by Django 4.1.7 on 2023-05-04 15:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ripc', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='answer',
            name='file_link',
        ),
        migrations.RemoveField(
            model_name='complect',
            name='file_link',
        ),
        migrations.RemoveField(
            model_name='scannedpage',
            name='file_link',
        ),
        migrations.RemoveField(
            model_name='task',
            name='file_link',
        ),
        migrations.RemoveField(
            model_name='variant',
            name='file_link',
        ),
        migrations.RemoveField(
            model_name='variant',
            name='page_len',
        ),
        migrations.AddField(
            model_name='answer',
            name='file_path',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='complect',
            name='file_path',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='scannedpage',
            name='file_path',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='task',
            name='file_path',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='variant',
            name='file_path',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='organizationevent',
            name='percent_status',
            field=models.TextField(max_length=3),
        ),
    ]
