# Generated by Django 4.1.7 on 2023-05-04 17:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ripc', '0002_remove_answer_file_link_remove_complect_file_link_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='patterntask',
            name='name',
            field=models.CharField(default=None, max_length=300),
            preserve_default=False,
        ),
    ]
