# Generated by Django 4.1.7 on 2023-05-04 20:15

import django.contrib.postgres.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ripc', '0003_patterntask_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='VariantCropping',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('answer_coord', django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(), size=None)),
                ('task_file_path', models.TextField(null=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='task',
            name='answer_coord',
        ),
        migrations.RemoveField(
            model_name='task',
            name='file_path',
        ),
        migrations.AddField(
            model_name='task',
            name='cropping',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='ripc.variantcropping'),
            preserve_default=False,
        ),
    ]
