# Generated by Django 4.1.7 on 2023-05-08 18:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ripc', '0004_variantcropping_remove_task_answer_coord_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='organizationevent',
            name='organization',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='ripc.organization'),
        ),
        migrations.AlterField(
            model_name='organizationevent',
            name='percent_status',
            field=models.TextField(max_length=3, null=True),
        ),
    ]
