# Generated by Django 4.1.7 on 2023-05-08 18:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ripc', '0005_alter_organizationevent_organization_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='organizationevent',
            name='number_participants',
            field=models.TextField(max_length=5, null=True),
        ),
    ]
